# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 23:16
from __future__ import unicode_literals

import amazon.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('manufacturer', models.TextField(null=True)),
                ('model', models.TextField(null=True)),
                ('title', models.TextField()),
                ('feature_list', amazon.models.ArrayField(verbose_name='list of features')),
                ('image_list', amazon.models.ArrayField(verbose_name='list of images')),
                ('review_count', models.PositiveIntegerField(verbose_name='number of reviews')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('date_searched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'searches',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.Search'),
        ),
    ]
