# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('date_searched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'amazon searches',
            },
        ),
    ]
