# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.TextField()),
                ('feature_list', models.TextField()),
                ('image_list', models.TextField()),
                ('price', models.FloatField()),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('mpn', models.TextField(blank=True, null=True)),
                ('review_count', models.PositiveIntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AmazonSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=100)),
                ('date_searched', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'amazon searches',
            },
        ),
        migrations.CreateModel(
            name='EbayItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('html', models.TextField()),
                ('category_search', models.TextField()),
                ('category_name', models.TextField()),
                ('category_id', models.IntegerField()),
                ('manufacturer', models.CharField(max_length=65)),
                ('mpn', models.CharField(max_length=65)),
                ('upc', models.CharField(blank=True, max_length=12, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonItem', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='review',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lister.ItemReview'),
        ),
        migrations.AddField(
            model_name='amazonitem',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonSearch'),
        ),
    ]
