# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lister.models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.TextField()),
                ('feature_list', lister.models.ArrayField(verbose_name='list of features')),
                ('image_list', lister.models.ArrayField(verbose_name='list of images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('manufacturer', models.TextField(null=True)),
                ('model', models.TextField(null=True)),
                ('review_count', models.PositiveIntegerField(verbose_name='number of reviews')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amazonsearch',
            name='query',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='amazonitem',
            name='search',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonSearch'),
        ),
    ]
