# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreview',
            name='item',
        ),
        migrations.RemoveField(
            model_name='amazonitem',
            name='is_listed',
        ),
        migrations.RemoveField(
            model_name='ebayitem',
            name='review',
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='category_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='category_search',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='html',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonItem', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='manufacturer',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='mpn',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ebayitem',
            name='upc',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='ebayitem',
            name='date_listed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ItemReview',
        ),
    ]
