# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0002_auto_20160114_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
