# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0002_auto_20160107_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonsearch',
            name='query',
            field=models.CharField(max_length=100),
        ),
    ]
