# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0003_auto_20160108_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, null=True)),
                ('html', models.TextField(null=True)),
                ('category', models.IntegerField(null=True)),
                ('manufacturer', models.TextField(null=True)),
                ('mpn', models.TextField(null=True)),
                ('upc', models.CharField(blank=True, max_length=12, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='amazonitem',
            name='manufacturer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amazonitem',
            name='mpn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonItem'),
        ),
    ]
