# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import lister.models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0003_auto_20160107_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amazonitem',
            old_name='model',
            new_name='mpn',
        ),
        migrations.AlterField(
            model_name='amazonitem',
            name='feature_list',
            field=lister.models.ArrayField(),
        ),
        migrations.AlterField(
            model_name='amazonitem',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
