# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0004_auto_20160109_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='category',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='html',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='manufacturer',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='mpn',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='title',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
