# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0004_auto_20160107_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonitem',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
