# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0005_amazonitem_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonitem',
            name='note',
        ),
    ]
