# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0005_auto_20160117_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebayitem',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
