# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0005_auto_20160110_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
