# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0006_itemreview_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='manufacturer',
            field=models.CharField(max_length=65),
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='mpn',
            field=models.CharField(max_length=65),
        ),
    ]
