# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 22:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0006_ebayitem_is_reviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebayitem',
            old_name='is_reviewed',
            new_name='is_ready',
        ),
    ]
