# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-08 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0006_remove_amazonitem_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
