# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0008_itemreview_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemreview',
            name='category',
        ),
        migrations.AddField(
            model_name='itemreview',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemreview',
            name='category_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemreview',
            name='category_search',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonItem', unique=True),
        ),
    ]
