# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0009_auto_20160111_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemreview',
            old_name='category',
            new_name='category_id',
        ),
        migrations.AddField(
            model_name='itemreview',
            name='category_name',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
