# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0010_auto_20160112_0125'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemreview',
            name='category_search',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
