# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0010_auto_20160113_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lister.AmazonItem'),
        ),
    ]
