# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0011_auto_20160113_0216'),
        ('lister', '0013_ebayitem'),
    ]

    operations = [
    ]
