# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lister', '0014_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebayitem',
            name='review',
        ),
        migrations.AlterField(
            model_name='amazonsearch',
            name='query',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='EbayItem',
        ),
    ]
